# This is a basic workflow that is manually triggered

name: Manage

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Command to Execute from File'
        default: 'runserver'
        required: true
      file:
        description: 'File'
        default: 'KPW/manage.py'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  execute:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # python KPW/manage.py ${{ github.event.inputs.name }}
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner.
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run command over manage.py
      run: |
        python -m pip install Django
        python ${{ github.event.inputs.file }} ${{ github.event.inputs.name }}
